#!/usr/bin/python3

from http.server import HTTPServer, BaseHTTPRequestHandler
import ssl
import re
import os

PATH = "/home/cola/android-javascript-game-files"

FILE_NOT_FOUND_MESSAGE = b"File not found"

def endswith(path, suffix):
	return path[-len(suffix):] == suffix

class Handler(BaseHTTPRequestHandler):
	def do_GET(self):
		assert self.path[0] == "/"
		path = self.path[1:]
		if path == "":
			path = "index.html"
		match = re.match(r'^[-a-zA-Z0-9.,/]*$', path)
		if match:
			try:
				f = open(os.path.join(PATH, path), "rb")
				buf = f.read()
				f.close()
			except FileNotFoundError:
				self.send_response(404)
				self.end_headers()
				self.wfile.write(FILE_NOT_FOUND_MESSAGE)
				buf = None
			if buf is not None:
				if endswith(path, ".js"):
					type = "text/javascript"
				elif endswith(path, ".css"):
					type = "text/css"
				elif endswith(path, ".ttf"):
					type = "font/ttf"
				else:
					type = "text/html"
				self.send_response(200)
				self.send_header("Content-type", type)
				self.send_header("Content-length", len(buf))
				self.end_headers()
				self.wfile.write(buf)
		print(self.path)

httpd = HTTPServer(('localhost', 9000), Handler)
httpd.socket = ssl.wrap_socket(
	httpd.socket,
	keyfile='serverkeys/key.pem',
	certfile='serverkeys/cert.pem',
	server_side = True
)
httpd.serve_forever()
